### ISSUE TITLE
Action stopped working

### ISSUE THREAD

**Issue by TomerFi** [prologic/action-markdownlint#2]
Great action - Thanks!

Starting today, I'm getting this message.
No modifications were made on my end, of course, this started happening today out-of-the-blue.

```text
reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?
```

This is my configuration:

```yaml
      - name: Lint markdown files
        uses: prologic/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
```

Any thoughts on the manner please?
